# coding: utf-8

"""
    Artifacts API

     Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json   # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GETransactionSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'object',
        'quantity': 'object',
        'price': 'object',
        'total_price': 'object'
    }

    attribute_map = {
        'code': 'code',
        'quantity': 'quantity',
        'price': 'price',
        'total_price': 'total_price'
    }

    def __init__(self, code=None, quantity=None, price=None, total_price=None):  # noqa: E501
        """GETransactionSchema - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._quantity = None
        self._price = None
        self._total_price = None
        self.discriminator = None
        self.code = code
        self.quantity = quantity
        self.price = price
        self.total_price = total_price

    @property
    def code(self):
        """Gets the code of this GETransactionSchema.  # noqa: E501

        Item code.  # noqa: E501

        :return: The code of this GETransactionSchema.  # noqa: E501
        :rtype: object
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GETransactionSchema.

        Item code.  # noqa: E501

        :param code: The code of this GETransactionSchema.  # noqa: E501
        :type: object
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this GETransactionSchema.  # noqa: E501

        Item quantity.  # noqa: E501

        :return: The quantity of this GETransactionSchema.  # noqa: E501
        :rtype: object
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this GETransactionSchema.

        Item quantity.  # noqa: E501

        :param quantity: The quantity of this GETransactionSchema.  # noqa: E501
        :type: object
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this GETransactionSchema.  # noqa: E501

        Item price.  # noqa: E501

        :return: The price of this GETransactionSchema.  # noqa: E501
        :rtype: object
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this GETransactionSchema.

        Item price.  # noqa: E501

        :param price: The price of this GETransactionSchema.  # noqa: E501
        :type: object
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def total_price(self):
        """Gets the total_price of this GETransactionSchema.  # noqa: E501

        Total price of the transaction.  # noqa: E501

        :return: The total_price of this GETransactionSchema.  # noqa: E501
        :rtype: object
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this GETransactionSchema.

        Total price of the transaction.  # noqa: E501

        :param total_price: The total_price of this GETransactionSchema.  # noqa: E501
        :type: object
        """
        if total_price is None:
            raise ValueError("Invalid value for `total_price`, must not be `None`")  # noqa: E501

        self._total_price = total_price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GETransactionSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GETransactionSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
